In [2]:
import pandas as pd
import numpy as np

In [3]:
df_kotor = pd.read_csv("../data/matchestill2018.csv")

In [4]:
df_kotor

Unnamed: 0        date   time            comp         round  day venue  \
0              0  2022-08-05  20:00  Premier League   Matchweek 1  Fri  Away   
1              1  2022-08-13  15:00  Premier League   Matchweek 2  Sat  Home   
2              2  2022-08-20  17:30  Premier League   Matchweek 3  Sat  Away   
3              3  2022-08-27  17:30  Premier League   Matchweek 4  Sat  Home   
4              4  2022-08-31  19:30  Premier League   Matchweek 5  Wed  Home   
...          ...         ...    ...             ...           ...  ...   ...   
4407          38  2018-04-15  16:00  Premier League  Matchweek 34  Sun  Away   
4408          39  2018-04-21  12:30  Premier League  Matchweek 35  Sat  Home   
4409          40  2018-04-28  15:00  Premier League  Matchweek 36  Sat  Away   
4410          41  2018-05-05  15:00  Premier League  Matchweek 37  Sat  Home   
4411          42  2018-05-13  15:00  Premier League  Matchweek 38  Sun  Away   

     result   gf   ga  ...  match report  notes    sh  sot  dist   fk   pk  \
0         W  2.0  0.0  ...  Match Report    NaN  10.0  2.0  14.6  1.0  0.0   
1         W  4.0  2.0  ...  Match Report    NaN  19.0  7.0  13.0  0.0  0.0   
2         W  3.0  0.0  ...  Match Report    NaN  14.0  6.0  14.8  0.0  0.0   
3         W  2.0  1.0  ...  Match Report    NaN  22.0  8.0  15.5  1.0  0.0   
4         W  2.0  1.0  ...  Match Report    NaN  22.0  8.0  16.3  1.0  0.0   
...     ...  ...  ...  ...           ...    ...   ...  ...   ...  ...  ...   
4407      W  1.0  0.0  ...  Match Report    NaN  10.0  4.0  18.1  0.0  0.0   
4408      D  2.0  2.0  ...  Match Report    NaN  13.0  6.0  17.7  0.0  0.0   
4409      W  1.0  0.0  ...  Match Report    NaN   9.0  2.0  20.1  0.0  0.0   
4410      W  1.0  0.0  ...  Match Report    NaN   9.0  1.0  10.2  0.0  0.0   
4411      L  0.0  2.0  ...  Match Report    NaN   7.0  1.0  24.8  1.0  0.0   

     pkatt season                  team  
0      0.0   2022               Arsenal  
1      0.0   2022               Arsenal  
2      0.0   2022               Arsenal  
3      0.0   2022               Arsenal  
4      0.0   2022               Arsenal  
...    ...    ...                   ...  
4407   0.0   2017  West Bromwich Albion  
4408   0.0   2017  West Bromwich Albion  
4409   0.0   2017  West Bromwich Albion  
4410   0.0   2017  West Bromwich Albion  
4411   0.0   2017  West Bromwich Albion  

[4412 rows x 28 columns]

In [5]:
df_kotor["round"].unique()

array(['Matchweek 1', 'Matchweek 2', 'Matchweek 3', 'Matchweek 4',
       'Matchweek 5', 'Matchweek 6', 'Matchweek 8', 'Matchweek 9',
       'Matchweek 10', 'Matchweek 11', 'Matchweek 13', 'Matchweek 14',
       'Matchweek 15', 'Matchweek 16', 'Matchweek 17', 'Matchweek 18',
       'Matchweek 19', 'Matchweek 20', 'Matchweek 21', 'Matchweek 22',
       'Matchweek 23', 'Matchweek 12', 'Matchweek 24', 'Matchweek 25',
       'Matchweek 7', 'Matchweek 26', 'Matchweek 27', 'Matchweek 28',
       'Matchweek 29', 'Matchweek 30', 'Matchweek 31', 'Matchweek 32',
       'Matchweek 34', 'Matchweek 35', 'Matchweek 36', 'Matchweek 33',
       'Matchweek 37', 'Matchweek 38'], dtype=object)

In [7]:
df_kotor.columns

Index(['Unnamed: 0', 'date', 'time', 'comp', 'round', 'day', 'venue', 'result',
       'gf', 'ga', 'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain',
       'formation', 'referee', 'match report', 'notes', 'sh', 'sot', 'dist',
       'fk', 'pk', 'pkatt', 'season', 'team'],
      dtype='object')

In [5]:
df_kotor["comp"]

0       Premier League
1       Premier League
2       Premier League
3       Premier League
4       Premier League
             ...      
4407    Premier League
4408    Premier League
4409    Premier League
4410    Premier League
4411    Premier League
Name: comp, Length: 4412, dtype: object

In [6]:
del df_kotor["comp"]

In [7]:
del df_kotor["notes"]

In [8]:
df_kotor["date"] = pd.to_datetime(df_kotor["date"])

In [9]:
df_kotor["target_home"] = (df_kotor["result"] == "W").astype("int")

In [10]:
df_kotor

Unnamed: 0       date   time         round  day venue result   gf   ga  \
0              0 2022-08-05  20:00   Matchweek 1  Fri  Away      W  2.0  0.0   
1              1 2022-08-13  15:00   Matchweek 2  Sat  Home      W  4.0  2.0   
2              2 2022-08-20  17:30   Matchweek 3  Sat  Away      W  3.0  0.0   
3              3 2022-08-27  17:30   Matchweek 4  Sat  Home      W  2.0  1.0   
4              4 2022-08-31  19:30   Matchweek 5  Wed  Home      W  2.0  1.0   
...          ...        ...    ...           ...  ...   ...    ...  ...  ...   
4407          38 2018-04-15  16:00  Matchweek 34  Sun  Away      W  1.0  0.0   
4408          39 2018-04-21  12:30  Matchweek 35  Sat  Home      D  2.0  2.0   
4409          40 2018-04-28  15:00  Matchweek 36  Sat  Away      W  1.0  0.0   
4410          41 2018-05-05  15:00  Matchweek 37  Sat  Home      W  1.0  0.0   
4411          42 2018-05-13  15:00  Matchweek 38  Sun  Away      L  0.0  2.0   

            opponent  ...  match report    sh  sot  dist   fk   pk pkatt  \
0     Crystal Palace  ...  Match Report  10.0  2.0  14.6  1.0  0.0   0.0   
1     Leicester City  ...  Match Report  19.0  7.0  13.0  0.0  0.0   0.0   
2        Bournemouth  ...  Match Report  14.0  6.0  14.8  0.0  0.0   0.0   
3             Fulham  ...  Match Report  22.0  8.0  15.5  1.0  0.0   0.0   
4        Aston Villa  ...  Match Report  22.0  8.0  16.3  1.0  0.0   0.0   
...              ...  ...           ...   ...  ...   ...  ...  ...   ...   
4407  Manchester Utd  ...  Match Report  10.0  4.0  18.1  0.0  0.0   0.0   
4408       Liverpool  ...  Match Report  13.0  6.0  17.7  0.0  0.0   0.0   
4409   Newcastle Utd  ...  Match Report   9.0  2.0  20.1  0.0  0.0   0.0   
4410       Tottenham  ...  Match Report   9.0  1.0  10.2  0.0  0.0   0.0   
4411  Crystal Palace  ...  Match Report   7.0  1.0  24.8  1.0  0.0   0.0   

     season                  team  target_home  
0      2022               Arsenal            1  
1      2022               Arsenal            1  
2      2022               Arsenal            1  
3      2022               Arsenal            1  
4      2022               Arsenal            1  
...     ...                   ...          ...  
4407   2017  West Bromwich Albion            1  
4408   2017  West Bromwich Albion            0  
4409   2017  West Bromwich Albion            1  
4410   2017  West Bromwich Albion            1  
4411   2017  West Bromwich Albion            0  

[4412 rows x 27 columns]

In [11]:
df_kotor[df_kotor["target_home"] == 0][["result", "target_home"]]

result  target_home
5         L            0
10        D            0
16        D            0
19        L            0
20        D            0
...     ...          ...
4404      L            0
4405      L            0
4406      D            0
4408      D            0
4411      L            0

[2710 rows x 2 columns]

In [12]:
df_kotor["target_away"] = (df_kotor["result"] == "L").astype("int")

In [15]:
df_kotor[df_kotor["result"] == "W" ][["result", "target_home", "target_away"]]

result  target_home  target_away
0         W            1            0
1         W            1            0
2         W            1            0
3         W            1            0
4         W            1            0
...     ...          ...          ...
4375      W            1            0
4396      W            1            0
4407      W            1            0
4409      W            1            0
4410      W            1            0

[1702 rows x 3 columns]

In [16]:
df_kotor["target_draw"] = (df_kotor["result"] == "D").astype("int")

In [19]:
df_kotor[["result", "target_home", "target_away", "target_draw"]]

result  target_home  target_away  target_draw
0         W            1            0            0
1         W            1            0            0
2         W            1            0            0
3         W            1            0            0
4         W            1            0            0
...     ...          ...          ...          ...
4407      W            1            0            0
4408      D            0            0            1
4409      W            1            0            0
4410      W            1            0            0
4411      L            0            1            0

[4412 rows x 4 columns]

In [20]:
df_kotor["venue_code"] = df_kotor["venue"].astype("category").cat.codes

In [24]:
df_kotor["venue_code"].unique()

array([0, 1], dtype=int8)

In [25]:
df_kotor["opp_code"] = df_kotor["opponent"].astype("category").cat.codes

In [30]:
df_kotor["opp_code"].unique()

array([ 8, 13,  2, 10,  1, 16,  3, 24, 14, 12, 21, 19,  7, 28, 27,  4, 17,
        9, 15,  0, 18,  5, 25, 20, 26, 11,  6, 22, 23], dtype=int8)

In [31]:
df_kotor["hour"] = df_kotor["time"].str.replace(":.+", "", regex=True).astype("int")

In [32]:
df_kotor["hour"].unique()

array([20, 15, 17, 19, 16, 12, 14, 13, 18])

In [33]:
df_kotor["day_code"] = df_kotor["date"].dt.dayofweek

In [34]:
df_kotor

Unnamed: 0       date   time         round  day venue result   gf   ga  \
0              0 2022-08-05  20:00   Matchweek 1  Fri  Away      W  2.0  0.0   
1              1 2022-08-13  15:00   Matchweek 2  Sat  Home      W  4.0  2.0   
2              2 2022-08-20  17:30   Matchweek 3  Sat  Away      W  3.0  0.0   
3              3 2022-08-27  17:30   Matchweek 4  Sat  Home      W  2.0  1.0   
4              4 2022-08-31  19:30   Matchweek 5  Wed  Home      W  2.0  1.0   
...          ...        ...    ...           ...  ...   ...    ...  ...  ...   
4407          38 2018-04-15  16:00  Matchweek 34  Sun  Away      W  1.0  0.0   
4408          39 2018-04-21  12:30  Matchweek 35  Sat  Home      D  2.0  2.0   
4409          40 2018-04-28  15:00  Matchweek 36  Sat  Away      W  1.0  0.0   
4410          41 2018-05-05  15:00  Matchweek 37  Sat  Home      W  1.0  0.0   
4411          42 2018-05-13  15:00  Matchweek 38  Sun  Away      L  0.0  2.0   

            opponent  ...  pkatt  season                  team  target_home  \
0     Crystal Palace  ...    0.0    2022               Arsenal            1   
1     Leicester City  ...    0.0    2022               Arsenal            1   
2        Bournemouth  ...    0.0    2022               Arsenal            1   
3             Fulham  ...    0.0    2022               Arsenal            1   
4        Aston Villa  ...    0.0    2022               Arsenal            1   
...              ...  ...    ...     ...                   ...          ...   
4407  Manchester Utd  ...    0.0    2017  West Bromwich Albion            1   
4408       Liverpool  ...    0.0    2017  West Bromwich Albion            0   
4409   Newcastle Utd  ...    0.0    2017  West Bromwich Albion            1   
4410       Tottenham  ...    0.0    2017  West Bromwich Albion            1   
4411  Crystal Palace  ...    0.0    2017  West Bromwich Albion            0   

     target_away target_draw venue_code opp_code  hour  day_code  
0              0           0          0        8    20         4  
1              0           0          1       13    15         5  
2              0           0          0        2    17         5  
3              0           0          1       10    17         5  
4              0           0          1        1    19         2  
...          ...         ...        ...      ...   ...       ...  
4407           0           0          0       16    16         6  
4408           0           1          1       14    12         5  
4409           0           0          0       17    15         5  
4410           0           0          1       24    15         5  
4411           1           0          0        8    15         6  

[4412 rows x 33 columns]